### ISSUE TITLE
Doubled imports in nodes.yaml

### ISSUE THREAD

**Issue by johscheuer** [bechtoldt/saltbox-vagrant#8]
Hi,

is there a reason why some of the salt-formulas are imported multiple times? For example:

[saltbox-1](https://github.com/bechtoldt/saltbox-vagrant/blob/master/nodes.yaml.dist#L28)
[saltbox-2](https://github.com/bechtoldt/saltbox-vagrant/blob/master/nodes.yaml.dist#L60)

I think also vim ist doubled.

If there is no reason I would clean them and send a PR

**Comment by arnisoph** [comment]
:clap: 

Please clean them up. :)
